### ISSUE TITLE
there's any way to keep connected the ble when app stopped?

### ISSUE THREAD

**Issue by marcolettieri** [Ladvien/Carduino#2]
there's any way to keep connected the ble when app stopped?
in background still work but if i leave and return in proximity or if the app is stopped i lose forever the connection until i reopen the app

**Comment by Ladvien** [comment]
This is an old project, which I'm no longer active in.  Please refer to https://github.com/Ladvien/behavioralBluetooth.  Also, if you have a question it'd probably best to email me rather than open an issue.

honeysucklehardware@gmail.com
